source 'https://rubygems.org'

gem 'rails',                            '4.2.4'
gem 'sqlite3'
gem 'sass-rails',                       '~> 5.0'
gem 'uglifier',                         '>= 1.3.0'
gem 'coffee-rails',                     '~> 4.1.0'
gem 'jquery-rails'
gem 'bcrypt', '~> 3.1.7'
gem 'active_model_serializers'

group :test, :development do
  gem 'factory_girl_rails'
  gem 'ffaker'
end

group :test do
  gem 'rspec-rails'
  gem 'sqlite3'
  gem 'shoulda-matchers'
  gem 'email_spec'
end

group :development, :test do
  #MySQL gem
  # gem 'mysql2'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
